name : AUTO-TEST

on :
# Trigger를 설정해줌
  push :
#   master branch로 push 요청이 들어왔을 때
    branches : [ master ]
  pull_request :
#   master branch로 PR 요청이 들어왔을 때
    branches : [ master ]

# 어떤 작업을 수행할지 설정
jobs :
  job1 :
# EC2가 ubuntu이니 ubuntu OS로 설정
    runs-on : ubuntu-latest
  
    steps :
      - name : Test with Gradle
        run : ./gradlew test

